apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarqube-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 50Gi
  nfs:
    server: 172.16.70.133
    path: "/nfsshare/sonarqube-data"
  claimRef:
    name: sonarqube-data
    namespace: labs-ci-cd
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: sonardb
spec:
    accessModes:
        - ReadWriteOnce
    capacity:
        storage: 50Gi
    nfs:
        server: 172.16.70.133
        path: "/nfsshare/sonardb"
    claimRef:
        name: sonardb
        namespace: labs-ci-cd
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: nexus
spec:
    accessModes:
        - ReadWriteOnce
    capacity:
        storage: 50Gi
    nfs:
        server: 172.16.70.133
        path: "/nfsshare/nexus"
    claimRef:
        name: nexus
        namespace: labs-ci-cd
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: jenkins
spec:
    accessModes:
        - ReadWriteOnce
    capacity:
        storage: 50Gi
    nfs:
        server: 172.16.70.133
        path: "/nfsshare/jenkins"
    claimRef:
        name: jenkins
        namespace: labs-ci-cd
