apiVersion: v1
kind: PersistentVolume
metadata:
  name: baloise-sonarqube-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 50Gi
  nfs:
    server: 172.16.70.133
    path: "/nfsshare/test-sonarqube-data"
  claimRef:
    name: sonarqube-data
    namespace: baloise-ci-cd
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: baloise-sonardb
spec:
    accessModes:
        - ReadWriteOnce
    capacity:
        storage: 50Gi
    nfs:
        server: 172.16.70.133
        path: "/nfsshare/test-sonardb"
    claimRef:
        name: sonardb
        namespace: baloise-ci-cd
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: baloise-nexus
spec:
    accessModes:
        - ReadWriteOnce
    capacity:
        storage: 50Gi
    nfs:
        server: 172.16.70.133
        path: "/nfsshare/test-nexus"
    claimRef:
        name: nexus
        namespace: baloise-ci-cd
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: baloise-jenkins
spec:
    accessModes:
        - ReadWriteOnce
    capacity:
        storage: 50Gi
    nfs:
        server: 172.16.70.133
        path: "/nfsshare/test-jenkins"
    claimRef:
        name: jenkins
        namespace: baloise-ci-cd
